#!/bin/bash

set -e

lein clean
lein uberjar

pushd library_test

$GRAALVM_HOME/bin/native-image \
    --report-unsupported-elements-at-runtime \
    --initialize-at-build-time \
    --no-fallback \
    --no-server \
    -H:+ReportExceptionStackTraces \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dtech.v3.datatype.graal-native=true \
    -jar ../target/dtype-next.jar \
    -cp classes \
    -H:Name=libdtype \
    --shared

popd
