#!/bin/bash

set -e

source scripts/activate-graal

#lein clean
#lein uberjar
graalvm/bin/native-image --report-unsupported-elements-at-runtime\
			 --initialize-at-build-time\
			 -jar target/dtype-next.jar tech.v3.datatype.main
