#!/bin/bash

if [ ! -e jdk-19.0.1 ]; then
    wget https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_linux-x64_bin.tar.gz
    tar -xvzf openjdk-19.0.1_linux-x64_bin.tar.gz
    rm openjdk-19.0.1_linux-x64_bin.tar.gz
fi

export PATH=$(pwd)/jdk-19.0.1/bin:$PATH
export JAVA_HOME=$(pwd)/jdk-19.0.1/
