#!/bin/bash

if [ ! -e jdk-17.0.1 ]; then
    wget https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz
    tar -xvzf openjdk-17.0.1_linux-x64_bin.tar.gz
    rm openjdk-17.0.1_linux-x64_bin.tar.gz
fi

export PATH=$(pwd)/jdk-17.0.1/bin:$PATH
export JAVA_HOME=$(pwd)/jdk-17.0.1/
